name: .NET CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Obtener código
      uses: actions/checkout@v4
    
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '10.0.x'
    
    - name: Restaurar paquetes
      run: dotnet restore
    
    - name: Compilar proyecto
      run: dotnet build --configuration Release --no-restore
    
    - name: Ejecutar pruebas
      run: dotnet test --no-build --verbosity normal
      continue-on-error: true

  frontend:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
    - name: Obtener código
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Instalar dependencias
      run: npm install
      working-directory: ./tasksis-frontend

    - name: Compilar proyecto frontend
      run: npm run build
      working-directory: ./tasksis-frontend

    - name: Ejecutar pruebas frontend
      run: npm run test --if-present
      working-directory: ./tasksis-frontend

  docker:
    runs-on: ubuntu-latest
    needs: [build, frontend]

    steps:
    - name: Obtener código
      uses: actions/checkout@v4

    - name: Construir imagen backend
      run: docker build -f TaskSis.Api/Dockerfile -t tasksis-api:latest ./TaskSis.Api

    - name: Construir imagen frontend
      run: docker build -t tasksis-frontend:latest ./tasksis-frontend

    - name: Ejecutar backend
      run: docker run -d -p 5255:5255 --name tasksis-api-container tasksis-api:latest

    - name: Ejecutar frontend
      run: docker run -d -p 5173:80 --name tasksis-frontend-container tasksis-frontend:latest

    - name: Esperar a que los contenedores estén listos
      run: sleep 5

    - name: Probar endpoint del backend
      run: curl -f http://localhost:5255/api/tareas || exit 1

    - name: Probar frontend
      run: curl -f http://localhost:5173 || exit 1

    - name: Validar que los contenedores están corriendo
      run: docker ps | grep tasksis-api-container && docker ps | grep tasksis-frontend-container

    - name: Detener contenedores
      run: |
        docker stop tasksis-api-container || true
        docker stop tasksis-frontend-container || true


