name: .NET CI Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest
    
    steps:
    - name: Obtener código
      uses: actions/checkout@v4
    
    - name: Setup .NET SDK
      uses: actions/setup-dotnet@v4
      with:
        dotnet-version: '10.0.x'
    
    - name: Restaurar paquetes
      run: dotnet restore
    
    - name: Compilar proyecto
      run: dotnet build --configuration Release --no-restore
    
    - name: Ejecutar pruebas
      run: dotnet test --no-build --verbosity normal
      continue-on-error: true

  frontend:
    runs-on: ubuntu-latest
    needs: build
    
    steps:
    - name: Obtener código
      uses: actions/checkout@v4

    - name: Setup Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Instalar dependencias
      run: npm install
      working-directory: ./tasksis-frontend

    - name: Compilar proyecto frontend
      run: npm run build
      working-directory: ./tasksis-frontend

    - name: Ejecutar pruebas frontend
      run: npm run test --if-present
      working-directory: ./tasksis-frontend
